### ISSUE TITLE
A proposal updating on draft & YANG module from Bo

### ISSUE THREAD

**Issue by YuChaode** [ietf-ccamp-wg/ietf-network-inventory#100]
Hi everyone,

In the past of few weeks, Bo had some discussions with me and she gave some advices if our data module wanted to be the core module:
1. remove some references which is optical-specific, such as ACTN, TMF and TAPI.
2. take software management into scope and remove hardware limitatiom both from draft and data module;
3. move topology reference data model to another single draft.

The attached files are the updated draft and data module, please have a look. We can have a discussion on this Wednesday's meeting. Tahnks! 
[draft-xxx-ivy-network-inventory-yang-00 (4).txt](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12509957/draft-xxx-ivy-network-inventory-yang-00.4.txt)
[ietf-network-inventory@2023-08-29.txt](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12511027/ietf-network-inventory%402023-08-29.txt)

**Comment by italobusi** [comment]
These are the diffs compared with the current I-D:

[Diff_ draft-ietf-ccamp-network-inventory-yang-02.txt - draft-xxx-ivy-network-inventory-yang-00.4.txt.zip](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12522045/Diff_.draft-ietf-ccamp-network-inventory-yang-02.txt.-.draft-xxx-ivy-network-inventory-yang-00.4.txt.zip)

https://author-tools.ietf.org/diff?doc_1=draft-ietf-ccamp-network-inventory-yang-02&url_2=https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12509957/draft-xxx-ivy-network-inventory-yang-00.4.txt

**Comment by YuChaode** [comment]
The slide presented by Wu Bo on 2023-09-06 weekly call:
[IETF network inventory use cases from draft-wzwb-opsawg-network-inventory.pptx](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12546315/IETF.network.inventory.use.cases.from.draft-wzwb-opsawg-network-inventory.pptx)

**Comment by YuChaode** [comment]
an update from Bo
[draft-xxx-ivy-network-inventory-yang-00 (2).txt](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12591841/draft-xxx-ivy-network-inventory-yang-00.2.txt)

**Comment by italobusi** [comment]
> an update from Bo [draft-xxx-ivy-network-inventory-yang-00 (2).txt](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12591841/draft-xxx-ivy-network-inventory-yang-00.2.txt)

If it helps, a diff comparing the new text proposal with the published CCAMP WG draft can be obtained using the following URL;

https://author-tools.ietf.org/diff?doc_1=draft-ietf-ccamp-network-inventory-yang-02&url_2=https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12591841/draft-xxx-ivy-network-inventory-yang-00.2.txt

**Comment by italobusi** [comment]
**[2023-09-06 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-09-06.md)**

Wu Bo presented some slides about the following use cases from draft-wzwb-opsawg-network-inventory-management and proposed the merged network inventory model :

1. Virtual devices, such as vCPE, vPE, vBNG, etc.
2. Software components, including device platform software, software patch, boot-rom, bootloader, etc.
3. Site as a location option
4. License list
5. Terms of network inventory, including network inventory, network element, and components
6. The merged network inventory model

The slides are available on github:

https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12546315/IETF.network.inventory.use.cases.from.draft-wzwb-opsawg-network-inventory.pptx

 
Here is some feedback and summary got on the call:

1. Some authors say virtual device, and software components are not considered, as the purpose of CCAMP inventory is to meet ACTN Packet Optical integration (POI) requirements for optical and IP multi-domain TE cases etc, https://datatracker.ietf.org/doc/html/draft-ietf-teas-actn-poi-applicability#section-4.
 
2. Some author shared the inventory information of Cisco vPE, indicating that virtual devices share the same inventory attributes just as physical devices:

~~~~
RP/0/RP0/CPU0:ron-srpce-791#show inventory all Wed Sep 6 14:50:04.239 UTC
NAME: "0/0", DESCR: "Cisco IOS-XRv 9000 Centralized Line Card"
PID: R-IOSXRV9000-LC-C, VID: V01, SN: B3BC8301B42 NAME: "0/0/0", DESCR: "N/A"
PID: PORT-1G-NIC, VID: N/A, SN: N/A NAME: "0/0/1", DESCR: "N/A"
PID: PORT-1G-NIC, VID: N/A, SN: N/A NAME: "0/0/2", DESCR: "N/A"
PID: PORT-1G-NIC, VID: N/A,SN: N/A NAME: "0/0/3", DESCR: "N/A"
PID: PORT-1G-NIC, VID: N/A, SN: N/A NAME: "0/0/4", DESCR: "N/A"
PID: PORT-1G-NIC, VID: N/A, SN: N/A NAME: "0/0/5", DESCR: "N/A"
PID: PORT-1G-NIC, VID: N/A, SN: N/A NAME: "0/0/6", DESCR: "N/A"
PID: PORT-1G-NIC, VID: N/A, SN: N/A
NAME: "0/RP0", DESCR: "Cisco IOS-XRv 9000 Centralized Route Processor"
PID: R-IOSXRV9000-RP-C, VID: V01, SN: 59D4943FFB2 NAME: "Rack 0", DESCR: "Cisco IOS-XRv 9000 Centralized Virtual Router"
PID: R-IOSXRV9000-CC, VID: V01, SN: 76E77892EA1
~~~~
 
3. The author has previously discussed the extension of sites and licenses.
 
4. The authors and contributors took a quick look at the merged model, and we plan to continue the discussion on this week.

**Comment by italobusi** [comment]
**[2023-09-13 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-09-13.md)**

There was no strong opinion to have or not separated roots for network-element and equipment-rooms

It has been noted that the current plan for the CCAMP WG draft is to generalize the model of equipment-rooms toward sites

There was discussion about whether equipment-rooms (sites) are or not part of the network inventory

In some UCs there is no need to report the equipment-rooms (sites) within the network inventory while in other UCs there is this need

The proposal to define equipment-rooms (sites) in a separated module would support a modular design where this module can be implemented only for the UCs where reporting the sites within the network inventory is required.

There was some discussion about the possibility to be more modular also when addressing SW components and licenses inventory requirements

However, it is not clear whether it is possible to achieve this objective through BC changes

For example, the inventory for licenses can be added through BC changes because the list of licenses is separated from other lists

The major technical issue is about adding SW components, through a BC changes, to a common list of HW and SW components. For example, the class attribute in the CCAMP WG draft cannot be extended in a BC way to support SW component types

It was mentioned that there are different options to update the component list in the CCAMP WG draft to allow adding SW component in a modular and BC way but there was no time to discuss them

It was agreed to work offline before the interim meeting to investigate the possibility to have a more modular and step-by-step approach for SW inventory

**Comment by italobusi** [comment]
This is an initial proposal on how the different pieces of the inventory can be split into multiple modules: [inventory-modular-design-00.txt](https://github.com/ietf-ccamp-wg/ietf-network-inventory/files/12662343/inventory-modular-design-00.txt)

**Comment by italobusi** [comment]
The comment from Med is tracked in https://github.com/sergiobelotti/network-inventory/issues/9
