### ISSUE TITLE
Proposal with schema-mount

### ISSUE THREAD

**Issue by oscargdd** [ietf-ccamp-wg/ietf-network-inventory#11]
augment /nw:networks/nw:network/nw:node {
      description
 "Augment used to define attach the node configuration";
 container commissioning-configs {
 uses system-config;
 uses protocols-config;
 uses resources-config;
 uses interfaces-config;
 }
 }

In system-config you would add the system configuration,

The rest are in case you want to expose the full device. 

I think this is the simplest way

**Comment by italobusi** [comment]
**[2021-11-17 Network Inventory call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2021-11-17.md)**

More than one draft in CCAMP WG has raised the issue about using schema mount. The suggestion is to progress the work focusing on the information to be provided and, in parallel, to investigate how schema mount can be used.

See: https://notes.ietf.org/notes-ietf-112-ccamp

**Comment by italobusi** [comment]
**2021-11-24 Network Inventory call**

- [ ] @vlopezalvarez : to present some ideas at the next call about how schema mount could be used

**Comment by italobusi** [comment]
**2021-12-01 Network Inventory call**

Presentation from Oscar

Aihua:for inventory we should mount just the "state" information not the "config" part. Is it possible with schema-mount.
You can control the with schema point where to add the schema mount but you cannot control what will be really mounted e.g. if only state

Anton: at implementation there is a pre-negotiation about which modules have to be mounted.


Need to discuss whether we need the flexibility for run-time or we are fine with the implementation time.

Aihua: I do not think we need the run-time flexibility, rather something to constraint which model can be mounted

Italo: I agree, we need somtething more design time and we might emulate this using the implementation time

Aihua: during the last IETF meeting there was a draft trying to constrain which model could be mounted. If we leave it to implementation time we risk to need a lot of implementation agreements when interop is required

Victor: this is what the operators are proposing in TIP, we need to consider whether this approach is good for IETF as well or whether the current approach is preferable

Anton: my preference is the schema mount since it allows for vendors to mount their own models

Jeff: but this what we would like to avoid. TIP is trying to speed-up real deployments so it is based also on implementation agreements such that all the TIP operators can ask all the vendors to follow that implentation agreement. The ultimate goal for operators is to speed-up interoperability.

Anton: there is no agreement on standard inventory models so there will be a standard data model with some gaps

Aihua: one possibility in IETF is to standardize a framework for inventory (with mount-points) and then standardize specific module e.g technology specific.

It would be beneficial to have a JSON example to understand better how the subtree schema is encompassed in the main schema structure.

- [ ] Victor/Oscar to check if it is possible to upload the TIP material shown today, taking into account IETF rules.

**Comment by italobusi** [comment]
[**2022-01-12 Network Inventory call**
](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2022-01-12.md)

Aihua: schema mount allows mounting any network inventory model. If our intention is to develop a standard inventory model, schema mount might not be the right option

Jeff: a possibility could be to have a generic fixed schema which where technology-specific information can be mounted. Maybe just doing a schema mount might not be sufficient to justify a new draft

Agreement to focus on defining a common generic model and then evaluate later the need to add some mount points to add additional information

**Comment by oscargdd** [comment]
Do we finally close this point as we are moving forward with the non-mount aproach?

**Comment by italobusi** [comment]
**[2023-03-22 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-03-22.md)**

Agreed to close this issue: no need to define any schema-mount with the current model and the model supporting the navigation between the network topology and the network hardware inventory models

**Comment by italobusi** [comment]
**[2023-05-17 Network Inventory weekly call](https://github.com/italobusi/ietf-network-inventory/blob/main/minutes/minutes-2023-05-17.md)**

Already discussed and agreed to close the issue
